Add controllers
kseniaGabbasova/java-shareit pull request #3
Opened 2022-09-20 23:53 UTC by kseniaGabbasova

2022-09-22 20:12 UTC, kukolev requested changes

2022-09-22 20:12 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-22 20:12 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-22 20:12 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-22 20:12 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/ItemServiceInMemoryImpl.java
> +            if (!itemToUpdate.getOwner().equals(item.getOwner())) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать.

2022-09-22 20:12 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-22 20:12 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
>  /**
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-09-22 20:12 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    String name;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-09-25 01:29 UTC, kseniaGabbasova commented
исправлены замечания второго ревью

2022-09-25 17:11 UTC, kukolev requested changes

2022-09-25 17:11 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/ItemServiceInMemoryImpl.java
> +    private boolean validateOwner(Item item, Item anotherItem) {
Текущая реализация по сути не отличается от предыдущей - в методе update количество кода не изменилось, но добавились два доп. метода. Код стал сложнее. 

Методы с валидацией лучше сделать так, чтобы они сами кидали исключения. При этом в методе update будет просто вызов validateOwner(...). Так будет разделены обязанности - валидация и выброс ошибок в одном методе, а логика обновления в другом.

Метод validateExistence нужно переделать по аналогии.

2022-09-27 02:47 UTC, kseniaGabbasova commented
исправлены методы валидации и метод update

2022-09-27 17:30 UTC, kukolev approved these changes

2022-10-03 12:57 UTC, merged