add-bookings
kseniaGabbasova/java-shareit pull request #4
Opened 2022-10-13 00:06 UTC by kseniaGabbasova

2022-10-13 16:44 UTC, kukolev requested changes

2022-10-13 16:44 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/ItemServiceImpl.java
> +            System.out.println(itemRepository.getReferenceById(id));
Логирование нужно делать с помощью логгера, а не просто выводить данные в консоль. Это важно, т.к. тогда можно будет управлять настройками логирования. Нужно поправить.

2022-10-13 16:44 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/ItemServiceImpl.java
> +public class ItemServiceImpl implements ItemService {
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-10-13 16:44 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-10-13 16:44 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/model/ItemServiceImpl.java
> +                    && !comment.getText().equals("")) {
Лучше сделать проверку так: `&& (!"".equals(comment.getText()))`. Тогда не будет выброшен NullPointerException, если text == null

2022-10-13 16:44 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
> +        return getClass().hashCode();
Текущая реализация фактически означает константный хэшкод. Это плохая практика, т.к. использование такого объекта в качестве ключа в HashMap/HashSet приведет уменьшению скорости доступа по ключу до O(n). Здесь это роли не играет, но вообще это плохая практика. Лучше воспользоваться авто-генерацией методов equals и hashCode в IDEA или написать метод самостоятельно, используя поля класса.

2022-10-14 01:52 UTC, kseniaGabbasova commented
исправлены ошибки первого ревью

2022-10-14 08:03 UTC, kukolev approved these changes

2022-10-16 00:45 UTC, merged