add-item-requests
kseniaGabbasova/java-shareit pull request #5
Opened 2022-11-28 02:08 UTC by kseniaGabbasova

2022-11-28 23:48 UTC, kseniaGabbasova commented
первое ревью

2022-11-29 17:16 UTC, kukolev requested changes

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingDto bookingDto = new BookingDto();
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingDto bookingDto1 = new BookingDto();
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    @Test
Тест не реализован. Нужно реализовать.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    @Test
Тест не реализован. Нужно реализовать.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        Assertions.assertEquals(bookingResult, List.of(booking2, booking1));
Здесь перепутаны местами параметры в assertEquals. На первом месте должен идти expected - ожидаемой значение. На втором месте actual - проверяемое значение. Это мелочь, но правильный порядок параметров это правила хорошего тона. Лучше сразу приучаться к общепринятой практике. Нужно поправить.

Аналогично нужно поправить и в остальных подобных случаях в других тестах.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    ItemService itemService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-29 17:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    ObjectMapper mapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-11-30 21:19 UTC, kseniaGabbasova commented
второе ревью

2022-12-01 18:22 UTC, kukolev approved these changes

2022-12-03 12:35 UTC, merged