add-docker
kseniaGabbasova/java-shareit pull request #6
Opened 2023-02-09 21:22 UTC by kseniaGabbasova

2023-02-10 18:12 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@RequestBody UserDto userDto) throws ValidationException {
Если создать пользователя два раза, то на второй раз клиенту приходит 500-я ошибка без описания.
На самом деле это не должно быть ошибкой на стороне сервера, а скорее Conflict

2023-02-10 18:13 UTC, EvgenyKoptubenko commented on server/src/main/java/ru/practicum/shareit/user/UserController.java
> +                          @RequestBody UserDto userDto) throws ValidationException {
Нельзя сделать патч пользователя два раза. Похоже дело в проверке email. Но может быть ситуация, когда email менять не нужно, а нужно поменять только login, например

2023-02-10 18:16 UTC, EvgenyKoptubenko commented
Если завести Item, потом сделать на него booking, то items/search выводит item, у которого не заполнены поля booking (но может так и надо)
	{
		"id": 2,
		"name": "nameItem",
		"description": "descriptionItem",
		"available": true,
		"requestId": null,
		"lastBooking": null,
		"nextBooking": null,
		"comments": null
	},

2023-02-10 18:20 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. По докеру замечаний нет.
Есть небольшие предложения по предыдущим итерациям, но если нет желания их править, то присылай обратно.

2023-02-10 21:16 UTC, kseniaGabbasova commented on server/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@RequestBody UserDto userDto) throws ValidationException {
Поменяла, теперь возвращает статус 409 с комментарием

2023-02-10 21:34 UTC, kseniaGabbasova commented on server/src/main/java/ru/practicum/shareit/user/UserController.java
> +                          @RequestBody UserDto userDto) throws ValidationException {
Вроде бы должно и так работать, в постам есть два теста: один на замену имейл, другой - на логин, отрабатывает нормально, так что ничего не меняла

2023-02-10 21:52 UTC, kseniaGabbasova commented
> Если завести Item, потом сделать на него booking, то items/search выводит item, у которого не заполнены поля booking (но может так и надо)
> {
> "id": 2,
> "name": "nameItem",
> "description": "descriptionItem",
> "available": true,
> "requestId": null,
> "lastBooking": null,
> "nextBooking": null,
> "comments": null
> },

букинги должны показываться только если идет получение через юзера, при условии, что он владелец, при обычном получении вещи букингом быть не должно

2023-02-10 21:52 UTC, kseniaGabbasova commented
> Работа сделана хорошо. По докеру замечаний нет.
> Есть небольшие предложения по предыдущим итерациям, но если нет желания их править, то присылай обратно.

Спасибо за ревью)

2023-02-11 17:34 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-11 21:15 UTC, merged